# Comparison Operators

In [3]:
import numpy as np
np_length = np.array([2.7, 3.4, 4.7, 6.6, 7.8])
np_breath = np.array([3.7, 1.4, 2.7, 3.6, 1.8])
np_height = np.array([1.7, 2.4, 1.7, 0.6, 1.8])
vol_cuboid = np_length * np_breath * np_height
vol_cuboid

array([16.983, 11.424, 21.573, 14.256, 25.272])

Show the vol_cuboid which are greater than 15

In [74]:
## Start code here
import numpy as np
np_length = np.array([2.7, 3.4, 4.7, 6.6, 7.8])
np_breath = np.array([3.7, 1.4, 2.7, 3.6, 1.8])
np_height = np.array([1.7, 2.4, 1.7, 0.6, 1.8])
vol_cuboid = np_length * np_breath * np_height
vol_cuboid

array([16.983, 11.424, 21.573, 14.256, 25.272])

In [75]:
vol_cuboid>15
## End here

array([ True, False,  True, False,  True])

In [77]:
vol_cuboid[vol_cuboid>15]

array([16.983, 21.573, 25.272])

## Numeric & Variable Comparison

Using comparison operators show:

Q1. If 10.5 is greater thean 10

Q2. If 10.5 is greater than equal to 10.5

Q3. If 20 is equal to 20.1

Q4. If Ansh is greater than Anshu

Q5. If Monkey is greater than 5

In [11]:
# 1
## Start code here
10.5>10
## End here

True

In [12]:
# 2
## Start code here
10.5>=10.5
## End here

True

In [14]:
# 3
## Start code here
20==20.1
## End here

False

In [80]:
# 4
## Start code here
a=["Ansh"]
b=["Anshu"]
## End here
a>b

False

In [116]:
# 5
## Start code here
"Monkey">"5"
## End here

True

## Boolean Operators

1. and
2. or
3. not

Q1. Use and operator to check if x is greater than 2 and less than 10

Q2. Use or operator to check if x is grater than 3 and less than 10

Q3. Use not operator to check if x is greater than 5 and less than 8

In [20]:
# 1
## Start code here
x=5
print(x>2 and x<10)
## End here

True


In [21]:
# 2
## Start code here
print(x>3 or x<10)
## End here

True


In [25]:
# 3
## Start code here
(x>5 and x<8)

False

In [28]:
not(x>5 and x<8)
## End here

True

## Numpy

1. logical_and()
2. logical_or()
3. logical_not()

Q1. Use the logical_and operator to check if vol_cuboid is greater than 11 and less than 20

Q2. Use the logical_or operator to check if vol_cuboid is greater than 11 and less than 20

Q3. Use the logical_not operator to check if vol_cuboid is greater than 11 and less than 20

In [61]:
# 1
## Start code here
import numpy as np
print(vol_cuboid)
np.logical_and(vol_cuboid>11,vol_cuboid<20)
## End here

[ 9 10 11 12]


array([False, False, False,  True])

In [47]:
# 2
## Start code here
np.logical_or(vol_cuboid>11,vol_cuboid<20)
## End here

array([ True,  True,  True,  True])

In [48]:
# 3
## Start code here
np.logical_not(vol_cuboid>11,vol_cuboid<20)
## End here

array([ True,  True,  True, False])

## if , elif , else

In [ ]:
a = 100
b = 10

Q1. Use if condition statment to check if a is greater than b and print the greatest number.

Q2. Use else condition statment to check if b is greater or less than a and print the greatest number.

Q3. Use elif condition statment to check if b is greater , less than or equal to a and print the greatest number.

In [25]:
# 1
## Start code here
a = 100
b = 10
if(a>b):
    print("The greatest number is:",a)
## End here

The greatest number is: 100


In [30]:
# 2
## Start code here
a = 100
b = 10
if(b>a):
    print("The greatest number is:",b)
else:
    print("b is less than a and the greatest number is",a)
## End here

b is less than a and the greatest number is 100


In [39]:
# 3
## Start code here
a = 100
b = 10
if(b>a):
    print("The greatest number is:",b)
elif(b<a):
    print("b is less than a and the greatest number is:",a)
else:
    print("b is equal to a")
## End here

b is less than a and the greatest number is: 100


## Filtering pandas Dataframes

In [ ]:
df = {
    "Name": ["aparna", "pankaj", "sudhir", "Geeku", "Chiku", "Jeniffer"], 
    "Degree": ["Bsc", "Engineering", "Law", "MBBS", "Phd", "Nursing"],
    "College": ["VIT", "IIT", "KIIT", "AIMS", "IIIT", "APPOLO"],
    "Score": [90, 70, 80, 98, 76, 89]} 

import pandas as pd
dataframe = pd.DataFrame(df)
dataframe

Q1. Access the Score column

Q2. Use comparison operator to show which students has score greater than 80

Q3. Use logical_and operator to see scores greater than 75 and less than 90

In [57]:
# 1
## Start code here
df = {
    "Name": ["aparna", "pankaj", "sudhir", "Geeku", "Chiku", "Jeniffer"], 
    "Degree": ["Bsc", "Engineering", "Law", "MBBS", "Phd", "Nursing"],
    "College": ["VIT", "IIT", "KIIT", "AIMS", "IIIT", "APPOLO"],
    "Score": [90, 70, 80, 98, 76, 89]} 
import pandas as pd
dataframe = pd.DataFrame(df)
dataframe
dataframe["Score"]
## End here

0    90
1    70
2    80
3    98
4    76
5    89
Name: Score, dtype: int64

In [51]:
type(dataframe["Score"])

pandas.core.series.Series

In [62]:
# 2
## Start code here
dataframe["Score"]>80

0     True
1    False
2    False
3     True
4    False
5     True
Name: Score, dtype: bool

In [64]:
dataframe[dataframe["Score"]>80]
## End here

Name   Degree College  Score
0    aparna      Bsc     VIT     90
3     Geeku     MBBS    AIMS     98
5  Jeniffer  Nursing  APPOLO     89

In [72]:
# 3
## Start code here
import numpy as np
dataframe[np.logical_and(dataframe["Score"]>75,dataframe["Score"]<90)]
## End here

Name   Degree College  Score
2    sudhir      Law    KIIT     80
4     Chiku      Phd    IIIT     76
5  Jeniffer  Nursing  APPOLO     89